# Python Functions

In [1]:
x = 1
y = 2
x + y

3

In [2]:
x

1

In [3]:
def add_numbers(x, y):
    return x + y

add_numbers(1,2)

3

In [4]:
def add_numbers(x, y, z):
    return x + y + z

add_numbers(1,2, 3)

6

In [6]:
def add_numbers(x, y, z = None):
    if z == None:
        return x + y
    else:
        return x + y + z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


- Python allows optional parameters in the function declaration.
- All optional paramenters should be placed after the mandatory parameters at the end in the function declaration.

In [7]:
def add_numbers(x, y, z = None, flag=False):
    if (flag):
        print ('Flag is true')
    if z == None:
        return x + y
    else:
        return x + y + z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))
print(add_numbers(1, 2, flag=True))

3
6
Flag is true
3


- Python allows assigning a function to a variable.
- We can assign a function to a variable, by doing so, we can pass that variable into other functions, allowing some basic functional programming.

In [8]:
def add_numbers(x, y):
    return x + y
    
a = add_numbers
a(2,3)

5

# Types and sequences

In [9]:
type('String')

str

In [10]:
type(None)

NoneType

In [11]:
type(5)

int

In [12]:
type(1.01)

float

In [13]:
type(add_numbers)

function

- Builtin `type` function tells which type the given reference is of.
- See examples above.
- Typed objects have properties associated with them, can be data or functions. 

## Three native kinds of collections in Python
- Tuples
- Lists
- Dictionaries

### Tuples
 - Tuple is a sequence of variables which is immutable itself - has ordering, cannot be changed once created.
 - Written using parantheses
 - Can mix types inside a tuple.

In [15]:
x = (1, 'a', 2, 'b')
type(x)

tuple

### Lists
 - Similar to tuples, but can be mutable - can change the length, number of elements and the element values 
 - Declared using square brackets
 - Can change the contents of the list using different methods
     - Using the `append` function: adds elements (appends) to the end of the list
     - Using list indices

In [16]:
x = [1, 'a', 2, 'b']
type(x)

list

In [18]:
x.append(3.5)

In [19]:
print(x)

[1, 'a', 2, 'b', 3.5]


- Both `list`s and `tuple`s are iterable types - meaning, we can write loops to go through every value they hold
- The norm is to use a `for` loop to look at each item in the list
 - No typing is required

In [20]:
for item in x:
    print(item)

1
a
2
b
3.5


- We can also access elements of `list`/`tuple` like `arrays` using square bracket operator called the indexing operator.
- Some basic mathematical operations are allowed on lists and tuples.
- Examples:
 - Plus sign `+` concatenates lists
 - Asterisk `*` repeats the values of a list
 - `len` operator returns the length of the list
 - `in` operator looks at the *set membership* and returns boolean value of `True` if the item is present in the list, `False` otherwise.

In [21]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [22]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [23]:
[1] * 3

[1, 1, 1]

In [24]:
len(x)

5

#### Slicing operation
- Indexing operator (square brackets) allows us to submit multiple values, unlike array indexing in other languages like Java.
 - First parameter is the starting location.
     - If this is the only element, then one item is returned from the list, item being specified by the parameter/index.
 - Second parameter is the end of the slice.
     - The end is exclusive; i.e., if you do something like `myList[0:1]` only one element is returned the $0^{th}$ element.
 - *All strings are lists of characters*, so slicing works beautifully on them.
 - Indexing values can be negative; this means to index from the back of the string.
 - If we want to reference the start or end of the string, we simply leave the parameter empty.

In [25]:
x = "This is a string"
print(x[0])
print(x[0:1])
print(x[0:2])
print(x[-1]) # returns the last character of the string
print(x[-4:-2]) # returns all characters from 4th last to the 2nd last positions

T
T
Th
g
ri


In [26]:
print(x[8:]) # from 8th character to the end
print(x[:-5]) # from beginning to the 5th last character

a string
This is a s


- Slicing is a core component of the Python language and is a big part of scientific computing with Python.

#### Manipulating strings
- Slicing is not the only way to manipulate strings.
- A common operation is to split the string based on substrings.
    - We can use patterns to split the string as per need and segment it appropriately.
- All operations on list work on strings. `+` operator concatenates the strings `*` opertor repeates the given string.
- String type has an associated function called `split`
    - `split` breaks the string based on simple patterns.

In [27]:
firstname = "akshay"
lastname = "narayan"
print(firstname + ' ' + lastname)
print(firstname * 3)
print('aks' in firstname)

akshay narayan
akshayakshayakshay
True


In [28]:
firstname = "akshay narayan".split(' ')[0]
lastname = "akshay narayan".split(' ')[-1]
print(firstname)
print(lastname)

akshay
narayan


### Dictionaries 
- Labeled collection of items and do not have ordering.
- It is a collection of `key:value` pairs, similar to `map` in other languages.
    - To retrieve a value we need to provide the key.
- Denoted using curly braces.
    - While declaring we separate a pair of values using a colon `:`.
    - Value can be retrieved using the indexing operator (square bracket) by specifying the label in place of the index.
    - Types of indices and values can be anything
    - New values are added using the same indexing operator and specifying new label (or key) and value.
- Iterating over the values - there are a number of ways:
    - Iterate over the `keys` and retrieve the `values`
    - Iterate over the `values` themselves
    - Iterate over both the `keys` and `values` at once using the `items()` function
        - The last method is called *unpacking*.
        - Extracting values in list or tuple to different variables using an assignment statement
        - e.g. `x = [1, 2, 'three']` followed by `one, two, three = x`        

In [29]:
x = {'Akshay': 'gibberish@gmail.com', 'Narayan': 'gmail@gibberish.com'}
print(x['Akshay'])
print(x['Narayan'])

gibberish@gmail.com
gmail@gibberish.com


In [30]:
x['Blah'] = None

In [31]:
print(x)

{'Narayan': 'gmail@gibberish.com', 'Blah': None, 'Akshay': 'gibberish@gmail.com'}


In [32]:
# iterating over the keys
for name in x:
    print(x[name])

gmail@gibberish.com
None
gibberish@gmail.com


In [33]:
# iterating over the values
for email in x.values():
    print(email)

gmail@gibberish.com
None
gibberish@gmail.com


In [34]:
# iterating over the keys and values
for name,email in x.items():
    print (name, ":", email)

Narayan : gmail@gibberish.com
Blah : None
Akshay : gibberish@gmail.com


In [35]:
type(lambda x: x+1)

function

### Strings
- By default strings in Python 3.5 are UTF (Unicode Transformation Format) and can read strings in international character sets.
- Due to dynamic typing, we need to explictly cast (do the type conversion) non strings to strings using `str()` function. E.g: `print('five' + str(5))`
- Additionally Python provides a *mini language* for string formatting. 
    - This allows writing string statements with place holders for variables to beevaluated. 
    - Variables are then passed either 'named' or 'in order' as arguments. 
    - String formatting language allows various other manipulations, like controlling the number of decimal places for floating point numbers, prepending + sign for positive numbers, set alignment as left or right etc.,

In [36]:
# example for string formatting
sales_record = {'price': 5.25, 'num_items': 4, 'person' : 'Akshay'}

sales_statement = '{} bought {} item(s) at a price of {} each for total {}'

print(sales_statement.format(sales_record['person'], 
                             sales_record['num_items'], 
                             sales_record['price'], 
                             sales_record['num_items']*sales_record['price']))

Akshay bought 4 item(s) at a price of 5.25 each for total 21.0


## Tutorial - Summary statistics from CSV files

In [38]:
import csv

%precision 2

with open('course1_downloads/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3]

[{'': '1',
  'class': 'compact',
  'cty': '18',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(l5)',
  'year': '1999'},
 {'': '2',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m5)',
  'year': '1999'},
 {'': '3',
  'class': 'compact',
  'cty': '20',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '31',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m6)',
  'year': '2008'}]

In [39]:
len(mpg)

234

In [40]:
mpg[0].keys()

dict_keys(['', 'trans', 'manufacturer', 'fl', 'displ', 'hwy', 'year', 'cty', 'class', 'cyl', 'model', 'drv'])

#### Task: Find the average MPG across all cars in the CSV file

In [42]:
# Average city MPG: sum the city mpg entry across all dictionaries in the list and divide by length of the list
print("Average MPG across all cars:" + str(sum(float(d['cty']) for d in mpg)/len(mpg)))

Average MPG across all cars:16.858974358974358


In [43]:
# Average highway MPG: sum highway mpg entry across all car-dictionaries in the list and divide by lenght of the list
print("Average MPG across all cars:" + str(sum(float(d['hwy']) for d in mpg)/len(mpg)))

Average MPG across all cars:23.44017094017094


#### Task: Find the average MPG across all cars in the CSV file, grouped by the number of cylinders a car has

In [44]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [56]:
cityMpgByCyl = []

for c in cylinders:
    summpg = 0
    cyl_type_count = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyl_type_count += 1
    cityMpgByCyl.append((c, summpg/cyl_type_count))

cityMpgByCyl.sort(key = lambda x: x[0])
print(cityMpgByCyl)

[('4', 21.012345679012345), ('5', 20.5), ('6', 16.21518987341772), ('8', 12.571428571428571)]


#### Task: Find the average MPG across all cars in the CSV file, grouped by the vehicle class

In [57]:
vehicle_class = set(d['class'] for d in mpg)
print(vehicle_class)

{'midsize', 'compact', 'suv', 'minivan', '2seater', 'pickup', 'subcompact'}


In [59]:
hwy_mpg_by_class = []

for c in vehicle_class:
    summpg = 0
    class_type_count = 0
    for d in mpg:
        if d['class'] == c:
            summpg += float(d['hwy'])
            class_type_count += 1
    hwy_mpg_by_class.append((c, summpg/class_type_count))
    
hwy_mpg_by_class.sort(key=lambda x: x[0])
print(hwy_mpg_by_class)

[('2seater', 24.8), ('compact', 28.29787234042553), ('midsize', 27.29268292682927), ('minivan', 22.363636363636363), ('pickup', 16.87878787878788), ('subcompact', 28.142857142857142), ('suv', 18.129032258064516)]


In [60]:
hwy_mpg_by_class.sort(key=lambda x: x[1])
print(hwy_mpg_by_class)

[('pickup', 16.87878787878788), ('suv', 18.129032258064516), ('minivan', 22.363636363636363), ('2seater', 24.8), ('midsize', 27.29268292682927), ('subcompact', 28.142857142857142), ('compact', 28.29787234042553)]


# Date and time

- Epoch: Jan 1, 1970.
- Like many other languages, times are sometimes stored as number of seconds or milliseconds from the epoch.
    - `time` module gives the current time since epoch
    - This time value needs to be converted to correct format to make sense of the date and time
- `fromtimestamp` method in `datetime` module can be used to convert the timestamp to readable format

In [61]:
import datetime as dt
import time as tm

In [62]:
tm.time()

1479281293.02

In [63]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2016, 11, 16, 15, 30, 57, 47670)

In [64]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2016, 11, 16, 15, 30, 57)

- Time deltas are used for some basic math operation using time; can be used to create sliding windows
    - e.g. get the date 7 days ago

In [65]:
delta = dt.timedelta(days=7) # gives a 7 day time delta
delta

datetime.timedelta(7)

In [66]:
today = dt.date.today()
today -delta

datetime.date(2016, 11, 9)

# `map` function

- Basis for functional programming in Python.
    - Side effect free programming
- Functional programming helps chaining operations together
    - Functional programming allows passing a function as a parameter of another function
    - Particularly useful in data cleaning and data preparation

- `map` function signature: `map(function, iterable, ...)`
    - The first parameter is the function that has to be executed.
    - The second and following parameters are something that can be iterated upon.
    - Returns an iterator that applies `function` to every element in the `iterable`, yielding the results. 
        - It doesn't return the list containign the results. 
        - This is due to lazy evaluation. 
        - Allows efficient memory management when dealing with big data.
        - Even if computation is heavy, the memory requirement is less as only concerned items are operated upon.
    - If additional `iterables` are passed (notices the "`...`"?), the `function` should take that many arguments.
    - The `function` is applied to items from all `iterables` in parallel.
    - All the iterable items are unpacked together and passed to the function
    
- Example:
    - Consider items' prices from two different stores and we need to find the minimum we have to pay if we bought the cheaper items between the two stores.
    - Traditional way to do this is to iterate through the list, compare the item prices and choose the cheapest.
    - `map` allows us to do this in one line.

In [67]:
store1 = [10.0, 11.0, 12.25, 2.50]
store2 = [9.0, 11.0, 12.25, 3.0]
cheapest = map(min, store1, store2)
cheapest

In [68]:
for c in cheapest:
    print (c)

9.0
11.0
12.25
2.5


#  `lambda`s and list comprehensions

- Pythons way of creating anonynmous functions - functions with no names; useful to get small simple stuff working withoug having to declare and code a function.
- Syntax:
    - Declare using the keyword `lambda` followed by a list of arguments, followed by a colon `:` and a single expression.
- The key difference between lambdas and normal functions is that in a lambda  there is only one expression to be evaluated.
- The expression value is returned on execution of the `lambda`
    - Return of lambda is a function reference.

- **Note**: 
    - We cannot have default values for lambdas
    - We cannot have complex logic inside of the lambda since it is limited to one expression.  

In [69]:
my_func = lambda a,b,c: a+b
my_func(1,2,3)

3

In [70]:
# Task: split the name to get salutation followed by last name
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

# traditional function way
def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1: the lambda way with looping
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2: the lambda way with map
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

# list comprehension
- An easy readable way to generate a list of items, more Pythonic and often faster than iteration.

In [71]:
# task: convert the following function to list comprehension
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i * j for i in range(10) for j in range(10)]

True

In [74]:
# Task: User ids are 2 letters followed by 2 numbers (e.g., aa49)
# Write an initialization line as a single list comprehension which creates a list of all possible user ids.
# Assume letters are all lower case

lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [i+j+k+l for i in lowercase for j in lowercase for k in digits for l in digits] 

In [75]:
answer[:20]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19']

# Intro to `numpy` 


In [76]:
import numpy as np

### Creating arrays

In [77]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [79]:
y = np.array([[7, 8, 9], [10, 11, 12]])
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [80]:
y.shape # returns the dimensionality of the array

(2, 3)

In [83]:
n = np.arange(10, 30, 2) # start, end, step End is exclusive

In [84]:
n

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [85]:
n = np.arange(0,36,1)
n.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [86]:
n.shape

(36,)

In [87]:
n = n.reshape(6,6)

In [88]:
n.shape

(6, 6)

In [89]:
n[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [90]:
n[::7]

array([[0, 1, 2, 3, 4, 5]])

In [91]:
n.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [92]:
n[:, ::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [93]:
n[2:4,2:4]

array([[14, 15],
       [20, 21]])

### Slicing/ Indexing

In [94]:
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [95]:
n.shape

(6, 6)

In [96]:
m = n.reshape(36)

In [97]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

- Using the above 2 arrays, we will see how to slice and dice numpy arrays and index operations.
<br>

- Indexing (1 dimension array):
    - We can use indices to retrieve the particular element in the array: `m[4]`
    - We can use colon notation to retrieve a range of elements in the array: `m[1:5]`
    - We can use negative indices to count back from the end of the array
    - The double colon operator: `::` specifies the start, end and step size

In [98]:
print(m[4])
print(m[1:5])
print(m[-4:])
print(m[-8::-2])

4
[1 2 3 4]
[32 33 34 35]
[28 26 24 22 20 18 16 14 12 10  8  6  4  2  0]


In [105]:
print(m[-8:-2:2]) # start from 8th last till second last (exclusive), traversing forward skipping by 2

[28 30 32]


In [106]:
print(m[-8:4:-2]) # start from 8th last till 4th element (exclusinve), traversing back skipping by 2

[28 26 24 22 20 18 16 14 12 10  8  6]


In [107]:
print(m[2:10:3]) # start from 3rd element till 10th skipping by 3 traversing forward

[2 5 8]


In [110]:
print(m[10:2:-3]) # start from 11th element till 2nd (exclusive) traversing back skipping 3

[10  7  4]


- Indexing (2 dimension array):
    - Comma notation to get the element in a specified location: `n[2,2]`
    - Slice of the row including columns specified: `n[2, 3:6]`
    - Get first 2 rows and all columns except the last: `n[:2, :-1]`
    - Select every 2 element from the last row: `n[-1, ::2]`
- Conditional assignment:
    - We can specify the condition in the brackets: `n[n > 20]`
    - Cap the max element in the array to 30: `n[n>30] = 30` ==> all elements above 30 will be set to 30 in this line   

In [113]:
print(n[2,2])
print(n[2, 3:6])
print(n[:2, :-1])
print(n[-1, ::2])
print(n[n > 20])
n[n>30]=30
print(n)

14
[15 16 17]
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]]
[30 32 34]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


- We can do assignments by splicing, but any change to the extracted splice is reflected in the original array

In [114]:
n = np.arange(0,36,1).reshape(6,6)

In [115]:
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [116]:
nn = np.arange(0,25,1).reshape(5,5)

In [117]:
nn_slice = nn[:3,:3]

In [118]:
nn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
nn_slice

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [120]:
nn_slice[:] = 0

In [121]:
nn_slice

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [122]:
nn

array([[ 0,  0,  0,  3,  4],
       [ 0,  0,  0,  8,  9],
       [ 0,  0,  0, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

- Notice how the extracted slice is also zero in the original array
- To circumvent this problem, we need to use the `copy` function

In [123]:
nn = np.arange(0,25,1).reshape(5,5)

In [124]:
nn_slice = nn[:3,:3].copy()

In [125]:
print(nn)
print(nn_slice)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


In [126]:
nn_slice[:]= 100

In [127]:
print(nn)
print(nn_slice)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]


### Iterating over arrays

- Iterate by row using `for row in array: ...`
- Iterate by row index using the length `len()` function which returns the number of rows
- We can combine the above 2 using `enumerate` which gives the row and the index of the row
- We can iterate through multiple arrays using the `zip()` function

In [128]:
test = np.random.randint(0,10,(4,3))

In [129]:
test

array([[0, 0, 0],
       [7, 0, 9],
       [7, 7, 7],
       [3, 9, 5]])

In [130]:
for row in test:
    print(row)

[0 0 0]
[7 0 9]
[7 7 7]
[3 9 5]


In [131]:
for i in range(len(test)): # len returns the number of rows
    print(test[i])

[0 0 0]
[7 0 9]
[7 7 7]
[3 9 5]


In [132]:
for i, row in enumerate(test):
    print('row: ', i, ' : ', row)

row:  0  :  [0 0 0]
row:  1  :  [7 0 9]
row:  2  :  [7 7 7]
row:  3  :  [3 9 5]


In [133]:
test2 = test**2 # square all elements of test and assign it to test2

In [134]:
test2

array([[ 0,  0,  0],
       [49,  0, 81],
       [49, 49, 49],
       [ 9, 81, 25]])

In [136]:
for i,j in zip(test, test2):
    print(i, '+', j ,' = ', i+j)

[0 0 0] + [0 0 0]  =  [0 0 0]
[7 0 9] + [49  0 81]  =  [56  0 90]
[7 7 7] + [49 49 49]  =  [56 56 56]
[3 9 5] + [ 9 81 25]  =  [12 90 30]
